#!/bin/bash
if [ x"${JAVA_ENABLE_DEBUG}" != x ] && [ "${JAVA_ENABLE_DEBUG}" != "false" ]; then
    java_debug_args="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=${JAVA_DEBUG_PORT:-5005}"
    echo "JAVA DEBUG ENABLED"
fi
java ${java_debug_args} -Djava.security.egd="file:/dev/./urandom" -jar "/@project.build.finalName@.jar"